- hosts: test
  tasks:
  - name: Install NIS
    when: ansible_os_family == "Linuxmint"
    apt: name={{item}} state=installed
    with_items:
        - rpcbind
        - nis
        - nfs-common

  - name: Install NIS
    when: ansible_os_family == "Archlinux" or ansible_os_family == "Manjaro Linux"
    pacman: name={{item}} state=installed
    with_items:
        - ypbind-mt
        - yp-tools

  - script: ./lightdm.sh
  - script: ./Mint_Install_NIS_NFS.sh