- hosts: test
  become: true
  tasks:
  # - name: Upgrade Arch
  #   when: ansible_os_family == "Archlinux"
  #   pacman:
  #     update_cache=yes
  #     upgrade=yes

  # - name: Install NIS
  #   when: ansible_os_family == "Archlinux"
  #   pacman: name={{item}} state=installed
  #   with_items:
  #       - rpcbind
  #       - nfs-utils

  # - name: Install NIS Debian
  #   when: ansible_os_family == "Debian" or ansible_os_family == 'Kali GNU/Linux'
  #   apt: name={{item}} state=installed
  #   with_items:
  #       - portmap
  #       - nis
  #       - nfs-common

  # - name: Creates directory for nis, see arch wiki
  #   file: path=/etc/systemd/system/systemd-logind.service.d state=directory

  - name: fix for systemd 239
    copy:
      src: /vsfs01/home/aspontarelli/ansible/scripts/open_network_interface.conf
      dest: /etc/systemd/system/systemd-logind.service.d/open_network_interface.conf

# AUR packages
  - name: create aur_builder user
    user:
      name: aur_builder
      group: wheel
      when: ansible_os_family == "Archlinux"
  - lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'
      when: ansible_os_family == "Archlinux"

  - name: openslp
    aur: name=openslp skip_installed=true
    become: yes
    become_user: aur_builder
    when: ansible_os_family == "Archlinux"

  - name: yp-tools
    aur: name=yp-tools skip_installed=true
    become: yes
    become_user: aur_builder
    when: ansible_os_family == "Archlinux"

  - name: ypbind-mt
    aur: name=ypbind-mt skip_installed=true
    become: yes
    become_user: aur_builder
    when: ansible_os_family == "Archlinux"

#   # - copy:
#   #     src: ../scripts/sleep_settings.sh
#   #     dest: /etc/profile.d
#   #     owner: root
#   #     group: root
#   #     mode: 0744

#   # - copy:
#   #     src: ../scripts/lightdm.conf
#   #     dest: /etc/lightdm/lightdm.conf
#   #     owner: root
#   #     group: root
#   #     mode: 0644

  - name: install user logout script
    copy:
      src: ../scripts/logout_users.sh
      dest: /etc/cron.daily/logout_users
      owner: root
      group: root
      mode: 0744

  - name: install NFS on Arch
    script: ../scripts/install_NIS_NFS.sh
    when: ansible_os_family == "Archlinux"

  - name: install NFS on Debian
    script: ../scripts/install_NIS_NFS-Debian.sh
    when: ansible_os_family == "Debian" or ansible_os_family == 'Kali GNU/Linux'
  # - script: ../scripts/lightdm.sh
