- hosts: clients
  become: true
  tasks:
  - name: Upgrade Arch
    pacman:
      update_cache=yes
      upgrade=yes

  - name: Install NIS
    pacman: name={{item}} state=installed
    with_items:
        - rpcbind
        - nfs-utils

# - name: AUR packages
  - aur: name=openslp user=adam
  - aur: name=yp-tools user=adam
  - aur: name=ypbind-mt user=adam

  - copy:
      src: ../scripts/sleep_settings.sh
      dest: /etc/profile.d
      owner: adam
      group: adam
      mode: 0744

  - copy:
      src: ../scripts/lightdm.conf
      dest: /etc/lightdm/lightdm.conf
      owner: adam
      group: adam
      mode: 0644

  - copy:
      src: ../scripts/logout_users.sh
      dest: /etc/cron.daily/logout_users.sh
      owner: adam
      group: adam
      mode: 0744

  # Logout idle users with idlekiller.sh
  # Requires script, service, and enabling the service
  - copy:
      src: ../scripts/idlekiller.sh
      dest: /usr/bin/idlekiller.sh
      owner: root
      group: root
      mode: 755
  - copy:
      src: ../scripts/idlekiller.service
      dest: /etc/systemd/system/idlekiller.service
      owner: root
      group: root
      mode: 755

  # - name: enable idle killer
  #   systemd:
  #     name: idlekiller.service
  #     enabled: True

  - script: ../scripts/install_NIS_NFS.sh
  - script: ../scripts/lightdm.sh
