- name: mount_vsfs01
  hosts: clients
  become: true
  become_method: su
  tasks:
    - name: Install NFS utils
      when: ansible_os_family == "Archlinux"
      pacman:
        name: nfs-utils
        state: present

    # - name: Enable nfsd kernel module
    #   when: ansible_os_family == "Archlinux"
    #   modprobe:
    #     name: nfsd
    #     state: present

    - name: Create vsfs01 directory
      file:
        path: /vsfs01
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Mount VSFS01 on Debian
      when: ansible_os_family == "Debian" or ansible_os_family == 'Kali GNU/Linux'
      mount:
        path: /vsfs01
        src: T5500b:/vsfs01
        fstype: nfs
        opts: rw,async,_netdev,x-systemd.automount
        state: present

    - name: Mount VSFS01 on Arch
      when: ansible_os_family == "Archlinux"
      mount:
        path: /vsfs01
        src: T5500b:/vsfs01
        fstype: nfs
        opts: rw,async,_netdev,noauto,x-systemd.automount
        state: present

    - name: manually mount vsfs01
      command: mount /vsfs01
      args:
        warn: no
