- hosts: test
  become: true
  become_method: su
  tasks:
    - name: Mount VSFS01 on Debian
      when: ansible_os_family == "Debian" or ansible_os_family == 'Kali GNU/Linux'
      mount:
        path: T5500b:/vsfs01
        src: /vsfs01
        fstype: nfs
        opts: rw,async,_netdev,x-systemd.automount
        state: present

    - name: Mount VSFS01 on Arch
      when: ansible_os_family == "Archlinux"
      mount:
        path: T5500b:/vsfs01
        src: /vsfs01
        fstype: nfs
        opts: rw,async,_netdev,noauto,x-systemd.automount
        state: present

    - name: mount all
      command: mount -a
      args:
        warn: no
