- hosts: clients
  become: yes
  tasks:

  - name: "Install Debian packages"
    when: ansible_os_family == "Debian" or ansible_os_family == 'Kali GNU/Linux'
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - python
      - git
      - arduino
      - python-matplotlib
      - python-numpy
      - python-scipy
      - python-pandas
      # - freecad
      - blender
      - emacs
      - kdenlive
      - nmap
      - libreoffice
      - librecad
      - gimp
      - inkscape
      - xfburn
      - python-h5py
      - octave
      - ghc
      - cups
      - zsh
      - ffmpeg
      - xfce4
      - gthumb

  - name: Install Arch packages
    when: ansible_os_family == "Archlinux"
    pacman: name={{item}} state=latest force=yes update_cache=yes
    with_items:
       - python
       - git
       - arduino
       - arduino-avr-core
       - python-matplotlib
       - python-numpy
       - python-scipy
       - python-pandas
       - python2-lxml
       - freecad
       - blender
       - emacs
       - kdenlive
       - nmap
       - libreoffice-still
       - librecad
       - gimp
       - inkscape
       - xfburn
       - tar
       - jupyter
       - python-h5py
       - octave
       - chromium
       - ghc
       - cups
       - zsh
       - ffmpeg
       - openscad
       - cmake
       - automake
       - filezilla
       - python-setuptools
       - kicad
       - audacity
       - vim
       - lua
       - gthumb
       - screen
       - llvm
       - clang
       - ansible
       - evince
       - gphoto2
       - manjaro-printer
       - wine-mono
       - wine_gecko
       - lib32-mpg123
       - kmag
       - frei0r-plugins
       - breeze-icon-theme
       - mlt
       - opencv
       - frei0r-plugins
       - breeze-icons
       - libnss_nis
       # # - lightdm
       # # - lightdm-gtk-greeter
       # # - light-locker

  - aur: name=sublime-text-dev user=adam
    when: ansible_os_family == "Archlinux"
  - aur: name=python2-power-git user=adam
    when: ansible_os_family == "Archlinux"
  - aur: name=cura-aleph-bin user=adam
    when: ansible_os_family == "Archlinux"
  - aur: name=rdworks-wine-bin user=adam
    when: ansible_os_family == "Archlinux"
