- hosts: new
  become: true
  tasks:
  - name: Remove Debian packages
    when: ansible_os_family == "Linuxmint"
    apt: name=xscreensaver state=absent

  - script: ../scripts/install_cura.sh

  - name: Install Debian packages
    when: ansible_os_family == "Linuxmint"
    apt: name={{item}} state=latest force=yes
    with_items:
         - python
         - git
         - arduino
         - python-matplotlib
         - python-numpy
         - python-scipy
         - python-pandas
         - freecad
         - blender
         - emacs
         - kdenlive
         - libreoffice
         - librecad
         - gimp
         - inkscape
         - r-base
         - gcc
         - okular
         - vlc
         - xfburn
         - openssh-server
         - tar
         - gfortran
         - g++
         - ipython-notebook
         - python-tables
         - python-h5py
         - octave
         - fritzing
         - texlive
         - chromium-browser
         - sublime-text
         - ghc
         - cups
         - lightdm
         - lightdm-gtk-greeter
         - light-locker
         - zsh
         - libav-tools
         - openscad
         - cmake
         - automake
         - build-essential
         - meshlab
         - filezilla
         - python-setuptools
         - kicad
         - audacity
         - vim
         - lua5.3
         - cura
         - gthumb
         - screen
         - llvm
         - clang
