- hosts: new
  become: true
  tasks:
  - name: Install Arch packages
    pacman: name={{item}} state=latest force=yes
    with_items:
         - python
         - git
         - arduino
         - python-matplotlib
         - python-numpy
         - python-scipy
         - python-pandas
         - freecad
         - blender
         - emacs
         - kdenlive
         # - libreoffice
         # - librecad
         # - gimp
         # - inkscape
         # - gcc
         # - okular
         # - vlc
         # - xfburn
         # - tar
         # - jupyter
         # - python-h5py
         # - octave
         # - chromium
         # - ghc
         # - cups
         # - lightdm
         # - lightdm-gtk-greeter
         # - light-locker
         # - zsh
         # - ffmpeg
         # - openscad
         # - cmake
         # - automake
         # - base-devel
         # - filezilla
         # - python-setuptools
         # - kicad
         # - audacity
         # - vim
         # - lua
         # - cura
         # - gthumb
         # - screen
         # - llvm
         # - clang
         # - ansible
         # - openssh

  # - script: ../scripts/install_cura.sh