- hosts: clients
  become: yes
  become_method: su
  tasks:

  - name: "Install Debian packages"
    when: ansible_os_family == "Debian" or ansible_os_family == 'Kali GNU/Linux'
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - python
      - git
      - arduino
      - python-matplotlib
      - python-numpy
      - python-scipy
      - python-pandas
      - blender
      - emacs
      - kdenlive
      - nmap
      - libreoffice always a conflict
      - librecad
      - gimp
      - inkscape
      - xfburn
      - python-h5py
      - octave
      - ghc
      - cups
      - zsh
      - ffmpeg
      - xfce4
      - gthumb
      - python-pip

    # needed to resolve most software conflicts
  # - name: full system upgrade
  #   when: ansible_os_family == "Archlinux"
  #   pacman:
  #     update_cache: yes
  #     upgrade: yes

  - name: Install Arch packages
    when: ansible_os_family == "Archlinux"
    pacman:
      name: ['python', 'git', 'arduino', 'arduino-avr-core', 'python-matplotlib', 'python-numpy', 'python-scipy', 'python-pandas', 'python2-lxml', 'blender', 'emacs', 'kdenlive', 'nmap', 'librecad', 'gimp', 'inkscape', 'xfburn', 'tar', 'jupyter', 'python-h5py', 'octave', 'chromium', 'ghc', 'cups', 'cups-pdf', 'zsh', 'ffmpeg', 'openscad', 'cmake', 'automake', 'filezilla', 'python-setuptools', 'kicad','kicad-library', 'audacity', 'vim', 'lua', 'gthumb', 'screen', 'llvm', 'clang', 'ansible', 'evince', 'gphoto2', 'manjaro-printer', 'lib32-mpg123', 'kmag', 'frei0r-plugins', 'breeze-icons', 'mlt', 'opencv', 'ttf-croscore', 'noto-fonts', 'ttf-cheapskate', 'pepper-flash', 'gvfs', 'krita', 'codeblocks', 'yay', 'mate', 'llvm-libs', 'shotcut', 'python-pip', 'sshpass']
      state: latest
      force: yes
      update_cache: yes

  - aur: name=openrocket skip_installed=true
    become: yes
    become_user: aur_builder
    when: ansible_os_family == "Archlinux"
  - name: Install Sublime-text
    aur: name=sublime-text-dev skip_installed=true
    become: yes
    become_user: aur_builder
    when: ansible_os_family == "Archlinux"
  - aur: name=python2-power-git skip_installed=true
    become: yes
    become_user: aur_builder
    when: ansible_os_family == "Archlinux"
  - aur: name=cura-aleph-bin skip_installed=true
    become: yes
    become_user: aur_builder
    when: ansible_os_family == "Archlinux"
  - aur: name=ansible-aur-git skip_installed=true
    become: yes
    become_user: aur_builder
    when: ansible_os_family == "Archlinux"

  # - pip:
  #   become: yes
  #   name: mu-editor
  #   when: ansible_os_family == "Archlinux"
  # - aur: name=freecad skip_installed=true
  #   become: yes
  #   become_user: aur_builder
  #   when: ansible_os_family == "Archlinux"
