- hosts: new
  become: yes
  tasks:
  # - script: ../scripts/refresh_package_keys.sh


  - name: Install Arch packages
    pacman: name={{item}} state=latest force=yes update_cache=yes
    with_items:
       - python
       - git
       - arduino
       - python-matplotlib
       - python-numpy
       - python-scipy
       - python-pandas
       - freecad
       - blender
       - emacs
       - kdenlive
       - nmap
       - libreoffice-still
       - librecad
       - gimp
       - inkscape
       - xfburn
       - tar
       - jupyter
       - python-h5py
       - octave
       - chromium
       - ghc
       - cups
       - zsh
       - ffmpeg
       - openscad
       - cmake
       - automake
       - filezilla
       - python-setuptools
       - kicad
       - audacity
       - vim
       - lua
       - gthumb
       - screen
       - llvm
       - clang
       - ansible
       - evince
       - gphoto2
       # # - lightdm
       # # - lightdm-gtk-greeter
       # # - light-locker


  - aur: name=sublime-text-dev user=adam
  - aur: name=python2-power-git user=adam
  - aur: name=cura-aleph-bin user=adam
