- name: system_administration
  hosts: clients
  become: true
  become_method: su
  tasks:

  # - name: fix for systemd 239
  #   copy:
  #     src: ../config_files/open_network_interface.conf
  #     dest: /etc/systemd/system/systemd-logind.service.d/open_network_interface.conf

  - name: enable NTP
    command: timedatectl set-ntp true

  # - name: openslp
  #   aur: name=openslp skip_installed=true
  #   become: yes
  #   become_user: aur_builder
  #   when: ansible_os_family == "Archlinux"

#   # - copy:
#   #     src: ../scripts/sleep_settings.sh
#   #     dest: /etc/profile.d
#   #     owner: root
#   #     group: root
#   #     mode: 0744

#   # - copy:
#   #     src: ../scripts/lightdm.conf
#   #     dest: /etc/lightdm/lightdm.conf
#   #     owner: root
#   #     group: root
#   #     mode: 0644

  - name: install user logout script
    copy:
      src: ../scripts/logout_users.sh
      dest: /etc/cron.daily/logout_users
      owner: root
      group: root
      mode: 0744

  - name: install group modification script
    copy:
      src: ../scripts/groups.sh
      dest: /etc/cron.hourly/groups
      owner: root
      group: root
      mode: 0744
