- name: user_management
  hosts: clients
  become: true
  become_method: su
  tasks:

    - name: "Put users in sensible Debian groups"
      when: ansible_os_family == "Debian"
      user:
        name: all
        groups: dialout, lp
        append: yes


    # - name: Remove vectorspace from sudo group
    #   when: ansible_os_family == "Debian"
    #   user:
    #     name: vectorspace
    #     groups: uucp, lock
    #     append: yes
